package com.moyz.adi.common.entity;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.databind.JsonNode;
import com.moyz.adi.common.base.JsonNodeTypeHandler;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.apache.ibatis.type.JdbcType;

/**
 * Draw对象
 */
@EqualsAndHashCode(callSuper = true)
@Data
@TableName(value = "adi_draw", autoResultMap = true)
@Schema(title = "Draw task", description = "Image generated by ai")
public class Draw extends BaseEntity {
    /**
     * 用户ID
     */
    @TableField("user_id")
    private Long userId;
    /**
     * UUID
     */
    @TableField("uuid")
    private String uuid;
    /**
     * AI模型ID
     */
    @TableField("ai_model_id")
    private Long aiModelId;
    /**
     * AI模型名称
     */
    @TableField("ai_model_name")
    private String aiModelName;
    /**
     * 提示词
     */
    @TableField("prompt")
    private String prompt;
    /**
     * negative提示词
     */
    @TableField("negative_prompt")
    private String negativePrompt;
    /**
     * generate数量
     */
    @TableField("generate_size")
    private String generateSize;
    /**
     * generateQuality
     */
    @TableField("generate_quality")
    private String generateQuality;
    /**
     * generateNumber
     */
    @TableField("generate_number")
    private Integer generateNumber;
    /**
     * generateSeed
     */
    @TableField("generate_seed")
    private Integer generateSeed;
    /**
     * dynamic参数
     */
    @TableField(value = "dynamic_params", jdbcType = JdbcType.JAVA_OBJECT, typeHandler = JsonNodeTypeHandler.class)
    private JsonNode dynamicParams;
    /**
     * original图片
     */
    @Schema(title = "file uuid")
    @TableField("original_image")
    private String originalImage;
    /**
     * mask图片
     */
    @Schema(title = "file uuid")
    @TableField("mask_image")
    private String maskImage;
    /**
     * respImages路径
     */
    @TableField("resp_images_path")
    private String respImagesPath;
    /**
     * generatedImages
     */
    @Schema(title = "generated image uuids")
    @TableField("generated_images")
    private String generatedImages;
    /**
     * interactingMethod
     */
    @TableField("interacting_method")
    private Integer interactingMethod;
    /**
     * process状态
     */
    @TableField("process_status")
    private Integer processStatus;
    /**
     * process状态描述
     */
    @TableField("process_status_remark")
    private String processStatusRemark;
    /**
     * 是否公开
     */
    @TableField("is_public")
    private Boolean isPublic;
    /**
     * withWatermark
     */
    @TableField("with_watermark")
    private Boolean withWatermark;
    /**
     * star数量
     */
    @TableField("star_count")
    private Integer starCount;
}
